name: 'Awaiting Reply'
description: 'This action adds an "Awaiting Reply" label to issues when a team member comments on an issue'
inputs:
    token:
        description: 'GitHub Token'
        required: false
        default: ${{ github.token }}
    awaiting-label:
        description: 'Label to toggle when a team member comments on an issue'
        required: true
        default: 'Awaiting Reply'
    replied-label:
        description: 'Label to toggle when the author of the issue comments'
        required: true
        default: 'Replied'
    ignore-labels:
        description: 'Ignore adding the label when these labels are present on the issue'
        required: false
    remove-labels:
        description: 'Additional labels to remove when the awaiting reply label is removed'
        required: false
    exclude-users:
        description: 'Ignore adding the label when these users comment on an issue'
        required: false
    remove-only-if-author:
        description: 'Remove the label only if the author of the issue comments'
        required: true
        default: 'true'
    ignore-string:
        description: 'Ignore adding the label if the comment contains this string'
        required: false
        default: '!ignore'
    debug:
        description: 'Enable debug mode'
        required: false
runs:
    using: 'node20'
    main: 'dist/index.js'
